### PR TITLE
Use native Node.js `fetch`

### PR DESCRIPTION
**Pull request by erbridge**
Since Node.js 17.5, Node.js has had native `fetch` support. This means we can no longer support Node.js 16.

### CODE REVIEW

**Review by zeke — APPROVED** [review]
Nice!

cc @gr2m

**Comment by zeke** [comment]
Wonder why that test is not running...

**Comment by zeke** [comment]
Testing passing for me locally.

**Comment by erbridge** [comment]
> Wonder why that test is not running...

Because we dropped support for Node.js 16 in doing this.

**Review by gr2m — COMMENTED** [review]
nice 👍🏼

**Pull request merged**
